/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eclipse.run.config.error;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("FROM GEN: "+new GeneratedClass().id);
    }
}
